config/routes.rb
Rails.application.routes.draw do
  resources :rules do
    resources :trades
  end
  devise_for :users

  resources :payments, only: [:show, :new]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # mount ActionCable.server => '/cable'
  get '/:page' => "pages#page"
  root to: 'pages#index'
end

app/views/shared/_drift.html.erb
<%- if Rails.env.production? %>

<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();

drift.SNIPPET_VERSION = '0.3.1';
drift.config({
  enableWelcomeMessage: false
});
drift.load('382p8m6ths2t');
</script>

<% end %>

app/views/shared/_flashes.html.slim
- flash.each do |type, message|
  p.notification[class="is-#{type}"]= message

app/views/shared/_hotjar.html.slim
javascript:
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1554181,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');

app/views/shared/_navbar.html.slim
nav.navbar
  .container
    .navbar-brand
      a.navbar-item[href=root_path]
        b 🔪 Bitcoin Knives
      span.navbar-burger.burger data-target="navbarMenuHeroA"
        span
        span
        span
    #navbarMenuHeroA.navbar-menu
      .navbar-end
        a.navbar-item.is-active[href=root_path]
          | Home
        / a.navbar-item[href='/download']
        /   | Download
        a.navbar-item[href='https://github.com/heelhook/bitcoinknives/' target='_blank']
          span.icon
            i.fab.fa-github
        a.navbar-item[href='https://twitter.com/pablof7z' target='_blank']
          span.icon
            i.fab.fa-twitter
        span.navbar-item
          - if current_user
            - if current_user.has_paid_plan?
              a.button.is-primary[href=rules_path]
                span Dashboard
            - else
              a.button[href=rules_path style='margin-right: 1rem;']
                span Dashboard
              a.button.is-primary[href='#' data-modal='upgrade-modal']
                span Upgrade
          - else
            a.button.is-primary.is-inverted[href=new_user_session_path style='margin-right: 1rem;']
              span Sign in
            a.button.is-primary[href=new_user_registration_path]
              span Sign up
        - if current_user
          = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'navbar-item'

app/views/shared/_upgrade_modal.html.slim
#upgrade-modal.modal
  .modal-background
  .modal-content
    .box
      .container.narrow.has-background-white
        .content.is-medium
          h2.subtitle Why upgrade?

          .columns.is-vcentered.is-mobile
            .column.is-3.has-text-centered
              <i class='uim uim-chart' style="--uim-color: #6563ff; zoom: 4;"></i>
            .column
              p
                b Preferred trade execution
                br
                span
                  | Trades are queued for execution. Paid subscribers get
                  |  bumped up on the queue for priority execution.

          .columns.is-vcentered.is-mobile
            .column.is-3.has-text-centered
              <i class='uim uim-layers-alt' style="--uim-color: #6563ff; zoom: 4;"></i>
            .column
              p
                b Mayer Multiple-aware
                br
                span
                  | Trades can be conditional on where the current bitcoin
                    price is with respect to the Mayer multiple, in order to
                    be more protected of swings when the price has deviated
                    from it's historical deviation.

          .columns.is-vcentered.is-mobile
            .column.is-3.has-text-centered
              <i class='uim uim-line-spacing' style="--uim-color: #6563ff; zoom: 4;"></i>
            .column
              p
                b Stack even more sats
                br
                span
                  | Blast through limits per trade and per month; stack
                  |  sats faster than the rest.

          .columns.is-vcentered.is-mobile
            .column.is-3.has-text-centered
              <i class='uim uim-process' style="--uim-color: #6563ff; zoom: 4;"></i>
            .column
              p
                b Support circular-economy bitcoin projects!
                br
                span
                  | Part of being a good bitcoin citizen is supporting
                  |  the circular-economy. We hold onto our sats, we don't
                  |  go convert them into fiat when we get them.

          .has-text-centered
            h1.title
              | 200k sats
              br
            h2.subtitle.is-3[style='font-weight: 300;']  per year

          .has-text-centered
            = link_to "⚡️ Upgrade Now ⚡️", new_payment_path, class: 'button is-primary is-large is-fullwidth'
            span[style='font-size: 0.8rem;']
              | On-chain or via LN | 200k sats = 0.002 btc = #{sats_to_dollars(200000)}


  button.modal-close.is-large[aria-label='close']