config/routes.rb
Rails.application.routes.draw do
  resources :rules do
    resources :trades
  end
  devise_for :users

  resources :payments, only: [:show, :new]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # mount ActionCable.server => '/cable'
  get '/:page' => "pages#page"
  root to: 'pages#index'
end

app/models/rule.rb
class Rule < ApplicationRecord
  extend FriendlyId
  friendly_id :uuid, use: [:slugged, :finders]
  belongs_to :user
  has_many :trades, dependent: :destroy

  validates :change_percentage, numericality: true
  validates :base_currency, presence: true
  validates :exchange_name, inclusion: { allow_blank: true, in: RuleConfigService.exchanges, message: 'is not valid' }
  validates :formula, inclusion: { in: RuleConfigService.formulas_human, message: 'is not valid' }
  validate :exchange_api_key_details, if: -> { exchange_api_key? && exchange_api_secret? }
  validate :max_sats_per_trade_limit, if: -> { exchange_name? }
  validates :max_sats_per_trade, numericality: true, if: -> { exchange_name? }

  default_scope -> { order(created_at: :desc) }
  scope :enabled, -> { where(enabled: true) }
  scope :configured, -> { where.not(exchange_name: nil, exchange_api_key: nil, exchange_api_secret: nil) }

  def uuid
    @uuid ||= SecureRandom.uuid
  end

  def configured?
    !exchange_name.blank? || !exchange_api_key.blank? || !exchange_api_secret.blank?
  end

  def running?
    enabled? && configured?
  end

  def tradable?
    configured? &&
    RuleTraderPolicy.rule_within_trade_limits?(self) &&
    sats_available_for_trade_in_period > 0
  end

  def max_sats_per_trade=(v)
    super convert_number(v)
  end

  def max_sats_per_period=(v)
    super convert_number(v)
  end

  def total_sats_traded_in_period
    period_limit = RuleConfigService.period_in_seconds(max_sats_per_period_length)

    trades
      .successful
      .where('created_at >= ?', period_limit.ago)
      .inject(0) { |mem, trade| mem + trade.amount } * 1e8
  end

  def sats_available_for_trade_in_period
    max_sats_per_period - total_sats_traded_in_period
  end

  private

  def convert_number(v)
    multiplier = case
    when v =~ /thousand/i, v =~ /k$/i then 1_000
    when v =~ /million/i, v =~ /m$/i then 1_000_000
    when v =~ /billion/i, v =~ /b$/i then 1_000_000_000
    when v =~ /btc$/i, v =~ /bitcoin$/i then 1e8
    else
      1
    end

    number = v.gsub(/[^0-9\.]/,'').to_f
    number * multiplier
  end

  def exchange_api_key_details
    if !RuleExchangeValidator.valid?(self)
      errors.add(:base, I18n.t('rule.validations.invalid_api_key'))
    end
  end

  def max_sats_per_trade_limit
    min_amount = RuleConfigService.trade_limit_for(exchange_name, type: 'min').to_f

    if min_amount > max_sats_per_trade
      errors.add(:max_sats_per_trade, "is too low, #{exchange_name}'s minimum purchase is #{min_amount.to_i} sats")
      self.max_sats_per_trade = min_amount.to_i
    end
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  before_action :load_rule_configs, only: [:new, :edit, :create, :update]
  before_action :authenticate_user!
  before_action :load_last_mm_tweet, only: [:new, :edit, :create, :update]

  # GET /rules
  # GET /rules.json
  def index
    @rules = current_user.rules.decorate
  end

  # GET /rules/new
  def new
    @rule = if params[:rule]
      Rule.new(rule_params)
    else
      Rule.new
    end.decorate
  end

  # GET /rules/1/edit
  def edit
    @rule = @rule.decorate
  end

  def show
    redirect_to edit_rule_path(@rule)
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)
    @rule.user = current_user

    respond_to do |format|
      if @rule.save
        format.html { redirect_to rules_path, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to rules_path, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.update(enabled: !@rule.enabled?)
    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  private

  def set_rule
    @rule = Rule.friendly.find(params[:id])
  end

  def load_rule_configs
    @formulas = RuleConfigService.formulas_human
    @exchanges = RuleConfigService.exchanges
    @periods = RuleConfigService.periods.map{|p| ["per #{p}", p]}
  end

  def load_last_mm_tweet
    @last_mm_tweet_id = LastMmTweetIdService.fetch
  end

  def rule_params
    permitted = [
      :change_percentage,
      :change_period,
      :formula,
      :base_currency,
      :enabled,
      :exchange_name,
      :exchange_api_key,
      :exchange_api_secret,
      :exchange_api_passphrase,
      :trade_notification,
    ]

    if current_user.has_paid_plan?
      permitted << :max_sats_per_trade
      permitted << :max_sats_per_period
      permitted << :max_period_in_secs
    end

    params.require(:rule).permit(permitted)
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.slim
= form_for @rule do |form|
  div[data-controller='rule-limits']
    - if rule.errors.any?
      section.section
        .container.narrow.is-centered
          - rule.errors.full_messages.each do |message|
            p.notification[class="is-danger"]
              button.delete
              = message

    section.hero.is-vcentered.is-light.is-primary.is-bold.is-medium
      .hero-body
        .container.narrow.has-text-centered
          div
            .content.is-large[style='line-height: 3rem;']
              ' When bitcoin falls by
              .control.is-inline
                .select.is-medium
                  = form.select :change_percentage, options_for_select((1..50).map{|i| ["#{i}%", i.to_f]}), class: 'input is-inline has-text-right'
              '  or more over
              .control.is-inline
                .select.is-medium
                  = form.select :change_period, @periods
            .content.is-large[style='line-height: 3rem;']
              '  buy
              .control.is-inline
                .select.is-medium
                  = form.select :formula, @formulas
              '  with
              .field.is-inline
                = form.text_field :base_currency, placeholder: 'USD', class: 'input is-medium is-inline', style: 'max-width: 5rem'

    section.section
      .container.narrow
        h2.subtitle.is-3[style='margin-bottom: 0.5rem;']
          ' Mayer Multiple
          span.tag.is-success Premium
        .columns
          .column.is-6
            .has-text-grey
              p This setting allows you to take into account the price of bitcoin in a historical context.
              p
                | You can read more about the Mayer Multiple <a href="http://mayermultiple.com" target='_blank'>here</a>.
              p
                a.button.is-small.is-primary[data-chat] Need help with this?
          .column.is-6
            .content
              = @last_mm_tweet_id

        .box[data-action=(!current_user.has_paid_plan? ? 'click->rule-limits#show_modal' : '')]
          .columns
            .column
              = form.radio_button :mayer_multiple, nil, class: 'is-checkradio'
              = form.label :mayer_multiple, 'Ignore the Mayer Multiple', class: 'label'

          .columns
            .column.is-8
              = form.radio_button :mayer_multiple, 'unit', class: 'is-checkradio'
              = form.label :mayer_multiple_unit, 'Only buy when the Mayer Multiple is lower than', class: 'label'
              p.has-text-grey A number lower than 2.4 is more conservative
            .column.is-4.has-text-right
              .control.is-inline
                .select
                  = select_tag :change_percentage, options_for_select((1..300).map{|i| i=i/100.0; ["#{i}", i]}, 2.4), disabled: !current_user.has_paid_plan?

          .columns
            .column.is-8
              = form.radio_button :mayer_multiple, 'percentage', class: 'is-checkradio'
              = form.label :mayer_multiple_percentage, 'Only buy when the Mayer Multiple has historically been higher', class: 'label'
            .column.is-4.has-text-right
              .control.is-inline
                .select
                  = select_tag :change_percentage, options_for_select((1..99).map{|i| ["#{i}% of the time", i.to_f]}, 50.0), disabled: !current_user.has_paid_plan?

    section.section
      .container.narrow
        h2.subtitle.is-3[style='margin-bottom: 0.5rem;']
          ' Limits
          span.tag.is-success Premium
        p.has-text-grey Set limits so Bitcoin Knives doesn't just take <b>all</b> sats out of circulation!
        .box
          .columns
            .column.is-8
              label.label[style='margin-bottom: 0;'] Per-trade limit
              p.has-text-grey Limit the number of sats to buy on a single trade
            .column.is-4[data-controller='sats-input']
              - if current_user.has_paid_plan?
                .control.has-icons-right
                  = form.text_field :max_sats_per_trade, class: 'input', 'data-target' => 'sats-input.input', 'data-action' => 'keyup->sats-input#update', autocomplete: 'off'
                  span.icon.is-right.has-text-grey[style='padding-right: 0.5rem;']
                    | sats
              - else
                .control.has-icons-right[data-action='click->rule-limits#show_modal']
                  = form.text_field :max_sats_per_trade, class: 'input', disabled: true, 'data-target' => 'sats-input.input', 'data-action' => 'keyup->sats-input#update', autocomplete: 'off'
                  span.icon.is-right.has-text-grey[style='padding-right: 0.5rem;']
                    | sats
              span.has-text-grey.content.is-small[data-target='sats-input.value']

          .columns
            .column.is-8
              label.label[style='margin-bottom: 0;'] Per-period limit
              p.has-text-grey Limit the number of sats to buy on a given period
            .column.is-4[data-controller='sats-input']
              .field.has-addons
                - if current_user.has_paid_plan?
                  .control.has-icons-right
                    = form.text_field :max_sats_per_period, class: 'input', 'data-target' => 'sats-input.input', 'data-action' => 'keyup->sats-input#update', autocomplete: 'off'
                    span.icon.is-right.has-text-grey[style='padding-right: 0.5rem;']
                      | sats
                - else
                  .control.has-icons-left[data-action='click->rule-limits#show_modal']
                    = form.text_field :max_sats_per_period, class: 'input', style: 'max-width: 12rem;', disabled: true, 'data-target' => 'sats-input.input', 'data-action' => 'keyup->sats-input#update', autocomplete: 'off'
                    span.icon.is-small.is-left
                      i.fas.fa-lock
                .control.is-inline[style='margin-left: 0.5rem;']
                  .select
                    - if current_user.has_paid_plan?
                      = form.select :max_sats_per_period_length, @periods, {}
                    - else
                      = form.select :max_sats_per_period_length, @periods, {}, "data-action" => 'change->rule-limits#show_modal', disabled: true
              span.has-text-grey.content.is-small[data-target='sats-input.value']

          - unless current_user.has_paid_plan?
            .columns.is-vcentered[style='margin-top: 1.5rem;']
              .column.is-3
                = image_tag 'undraw_chore_list_iof3.svg'
              .column
                p.content.is-large
                  | Want to stack more sats and get preferred execution?
                p
                  a.button.is-dark.is-large[href='#' data-modal='upgrade-modal']
                    span ⚡️ Upgrade ⚡️


    section.section
      .container.narrow
        h2.subtitle.is-3[style='margin-bottom: 0.5rem;'] Exchange
        .columns.is-vcentered[data-controller='rule-exchange']
          .column
            .box
              .columns
                .column.is-8
                  label.label Exchange
                .column.is-4
                  .control
                    .select
                      = form.select :exchange_name, (@exchanges+['Not listed']), {include_blank: true}, { "data-target" => "rule-exchange.exchange", "data-action" => "change->rule-exchange#display_correct_fields" }
              #fields.columns.hidden.kraken.coinbase_pro
                .column.is-4
                  = form.label :exchange_api_key, 'API Key', class: 'label'
                .column.is-8
                  .control
                    = form.text_field :exchange_api_key, class: 'input', autocomplete: 'off'
              #fields.columns.hidden.kraken.coinbase_pro
                .column.is-4
                  = form.label :exchange_api_secret, 'API Secret', class: 'label'
                .column.is-8
                  .control
                    = form.text_field :exchange_api_secret, class: 'input', autocomplete: 'off'
              #fields.columns.hidden.coinbase_pro
                .column.is-4
                  = form.label :exchange_api_passphrase, 'API Passphrase', class: 'label'
                .column.is-8
                  .control
                    = form.text_field :exchange_api_passphrase, class: 'input', autocomplete: 'off'
          .column.is-4
            .content
              #instructions
                .hidden.not_listed
                  h3.
                    | Can't find your exchange?

                  p
                    ' Send us a quick
                    a[href='https://twitter.com/pablof7z' target='_blank'] DM
                    '  or
                    a[data-chat] message
                    |  about it and we'll get it added as soon as possible.
                .hidden.coinbase_pro
                  p
                    ' Create an API key at
                    a[href='https://pro.coinbase.com/profile/api' target='_blank' style='font-size: 0.8rem;'] https://pro.coinbase.com/profile/api
                  p
                    | Make sure you enable the permissions:

                  p
                    b ✅ Trade
                    br
                    span[style='font-size: 0.8rem;']  In order to create orders.

                  p
                    ' You can enable IP whitelist with:
                    b 157.245.32.159
                .hidden.kraken
                  p
                    ' Create an API key at
                    a[href='https://www.kraken.com/u/settings/api' target='_blank' style='font-size: 0.8rem;'] https://www.kraken.com/u/settings/api
                  p
                    | Make sure you enable the permissions:

                  p
                    b ✅ Query Open Orders & Trades
                    br
                    span[style='font-size: 0.8rem;']  In order to create orders.

                  p
                    b ✅ Query Closed Orders & Trades
                    br
                    span[style='font-size: 0.8rem;']  In order to check when orders have executed.
                .hidden.cex
                  p
                    ' Create an API key at
                    a[href='https://cex.io/trade/profile#/api' target='_blank' style='font-size: 0.8rem;'] https://cex.io/trade/profile#/api
                  p
                    | Make sure you enable the permissions:

                  p
                    b ✅ Place orders
                    br
                    span[style='font-size: 0.8rem;']  In order to create orders.

                  p
                    ' You can enable IP whitelist with:
                    b 157.245.32.159

    section.section
      .container.narrow
        h2.subtitle.is-3[style='margin-bottom: 0.5rem;']
          | Settings
        .box
          .columns
            .column.is-8
              label.label[for="rule_enabled"] Allow this rule to run
              p.has-text-grey This switch allows you to temporarily pause this rule.
            .column.is-4.has-text-right
              .field
                = form.check_box :enabled, class: 'switch is-success is-rounded', type: 'checkbox'
                label[for="rule_enabled"]
          .columns
            .column.is-8
              label.label[for="rule_trade_notification"] Send trade notifications
              p.has-text-grey Receive email notifications when a trade was executed
            .column.is-4.has-text-right
              .field
                = form.check_box :trade_notification, class: 'switch is-success is-rounded', type: 'checkbox'
                label[for="rule_trade_notification"]

        .actions
          = form.submit 'Save', class: 'button is-large is-primary'

app/views/rules/edit.html.slim
= render 'form', rule: @rule

app/views/rules/index.html.slim
- if @rules.empty?
  section.hero.is-primary.is-bold.is-fullheight-with-navbar.is-vcentered
    .hero-body.has-text-centered
      .container
        h1.title[style="zoom: 4"] 🔪
        h1.title You ain't stacking nothing yet!
        .content.is-large
          p
            | You don't have any rules configured to stack sats
            |  like a boss yet.
          p Go ahead and get started!
        = link_to 'Add new buy rule', new_rule_path, class: 'button is-primary is-large is-rounded is-inverted'
- else
  section.section
    .container.narrow
      .columns.is-vcentered.is-centered.is-multiline
        - @rules.each do |rule|
          .column.is-three-quarters
            .card[class=rule.card_class data-controller='price-watcher' data-price-watcher-period=rule.change_period]
              .card-content[style='height: 17rem; overflow: scroll;']
                p.title[style='font-weight: normal;']
                  ' When bitcoin goes down by
                  b #{rule.change_percentage}% over #{rule.change_period}
                p.subtitle
                  | buy
                  code #{rule.formula}
                  |  with #{rule.base_currency}

                - if !rule.enabled?
                  .columns.is-mobile.is-vcentered
                    .column.is-1
                      h1.title 😴
                    .column.is-6[style='padding-left: 2rem;']
                      p This rule is currently disabled.
                - elsif !rule.configured?
                  .columns.is-mobile.is-vcentered
                    .column.is-1
                      h1.title 😔
                    .column.is-6[style='padding-left: 2rem;']
                      p You still need to complete the configuration to get this bad boy to run.
                    .column
                      a.button.is-primary[data-chat] Need help?

                - if rule.trades.successful.count > 0
                  p= "🙌🏻 #{number_to_human(rule.total_sats_traded)} sats stacked"
                - if !RuleTraderPolicy.rule_within_trade_limits?(rule.object)
                  p
                    | You've reached the stacking limit for this period, stacking #{number_to_human(rule.total_sats_traded_in_period)} sats in the past #{rule.max_sats_per_period_length}
                  p
                    = link_to 'Want to increase your limit?', edit_rule_path(rule)
                - elsif RuleTraderPolicy.rule_traded_within_change_period?(rule.object)
                  p
                    | Stacked #{time_ago_in_words(rule.last_trade_time)} ago,
                    |  waiting to stack again for #{time_ago_in_words(rule.next_trade_time)}

              .card-footer
                = link_to 'Edit', edit_rule_path(rule), class: 'button is-inverted is-primary is-fullwidth is-large card-footer-item'
                - if !rule.configured?
                  = link_to 'Configure', edit_rule_path(rule), class: 'button is-inverted is-primary is-fullwidth is-large card-footer-item'
                - elsif rule.trades.count > 0
                  = link_to pluralize(rule.trades.count, 'trade'), rule_trades_path(rule), class: 'button is-inverted is-primary is-fullwidth is-large card-footer-item'
                .card-footer-item
                  p[class=rule.price_change_class]
                    span[data-target='price-watcher.price']
                      = "#{rule.price_change.round(2)}%"
                    span'  over #{rule.change_period}


      .columns.is-centered
        .column.is-half
          = link_to 'Add new buy rule', new_rule_path, class: 'button is-primary is-large is-fullwidth'

app/views/rules/new.html.slim
= render 'form', rule: @rule

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rule.user_id %>
</p>

<p>
  <strong>Change percentage:</strong>
  <%= @rule.change_percentage %>
</p>

<p>
  <strong>Change period:</strong>
  <%= @rule.change_period %>
</p>

<p>
  <strong>Formula:</strong>
  <%= @rule.formula %>
</p>

<p>
  <strong>Max sats per trade:</strong>
  <%= @rule.max_sats_per_trade %>
</p>

<p>
  <strong>Max sats per period:</strong>
  <%= @rule.max_sats_per_period %>
</p>

<p>
  <strong>Max period in secs:</strong>
  <%= @rule.max_period_in_secs %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @rule.enabled %>
</p>

<p>
  <strong>Exchange name:</strong>
  <%= @rule.exchange_name %>
</p>

<p>
  <strong>Exchange api details:</strong>
  <%= @rule.exchange_api_details %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>